[modules.e2e]
source = ".dagger/modules/e2e"

[modules.fixtures]
source = ".dagger/modules/fixtures"

[modules.dang-sdk]
source = "github.com/dagger/dang-sdk"
# Marker filename that skips generate when found at or above a Dang SDK module root.
# settings.skipGenerateFilename = ""

[modules.dang-sdk.as-sdk]
name = "dang"

[[modules.dang-sdk.as-sdk.modules]]
path = "."

[[modules.dang-sdk.as-sdk.modules]]
path = ".dagger/modules/fixtures"

[[modules.dang-sdk.as-sdk.modules]]
path = ".dagger/modules/e2e"
