[modules.e2e]
source = ".dagger/modules/e2e"

[modules.fixtures]
source = ".dagger/modules/fixtures"

[modules.dang-sdk]
source = "github.com/dagger/dang-sdk"
# Marker filename that skips generate when found at or above a Dang SDK module root.
# settings.skipGenerateFilename = ""

[modules.dagger-dang-sdk]
source = "github.com/dagger/dang-sdk"

[sdks.dang]
module = "dagger-dang-sdk"

[sdks.dang.scopes."."]
is-module = true
name = "playwright"

[sdks.dang.scopes.".dagger/modules/fixtures"]
is-module = true

[sdks.dang.scopes.".dagger/modules/e2e"]
clients = ["./.", "./.dagger/modules/fixtures"]
is-module = true
